MyApp.Mvc/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MyApp.Application.Interfaces;
using MyApp.Domain.Models;
using MyApp.Domain.ViewModels.Products;

namespace MyApp.Mvc.Areas.Admin.Controllers
{
    public class ProductController : AdminBaseController
    {
        #region Fields

        private readonly IProductService _productService;

        #endregion

        #region Constructor

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        #endregion

        #region Public Methods

        #region List

        // GET: ProductController
        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetAllAsync();
            var productViewModels = products.Select(product => new ProductViewModel
            {
                Id = product.Id,
                Title = product.Title,
                Description = product.Description,
                Price = product.Price,
                ImageName = product.ImageName
            }).ToList();
            return View(productViewModels);
        }

        #endregion

        #region Details 

        // GET: ProductController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var product = await _productService.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        #endregion

        #region Create 

        // GET: ProductController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var product = new Product
                {
                    Title = viewModel.Title,
                    Description = viewModel.Description,
                    Price = viewModel.Price,
                    ImageName = viewModel.ImageName,
                };

                await _productService.AddAsync(product);
                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        #endregion

        #region Edit 

        // GET: ProductController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _productService.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            var viewModel = new EditProductViewModel
            {
                Id = product.Id,
                Title = product.Title,
                Description = product.Description,
                Price = product.Price,
                ImageName = product.ImageName,
            };

            return View(viewModel);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditProductViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var product = new Product
                {
                    Id = viewModel.Id,
                    Title = viewModel.Title,
                    Description = viewModel.Description,
                    Price = viewModel.Price,
                    ImageName = viewModel.ImageName,
                };

                await _productService.UpdateAsync(product);
                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        #endregion

        #region Delete

        // GET: ProductController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productService.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _productService.GetByIdAsync(id);
            if (product == null)
            {
                TempData["ErrorMessage"] = "Product not found.";
                return RedirectToAction(nameof(Index));
            }

            await _productService.DeleteAsync(id);
            TempData["SuccessMessage"] = "Product deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #endregion

    }
}

MyApp.Mvc/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using MyApp.Application.Interfaces;
using MyApp.Domain.Models;
using MyApp.Domain.ViewModels.Users;

namespace MyApp.Mvc.Areas.Admin.Controllers
{
    public class UserController : AdminBaseController
    {
        #region Fields
        private readonly IUserService _userService;
        #endregion

        #region Constructor
        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        #endregion

        #region Public Method

        #region List
        // GET: UserController
        public async Task<ActionResult> Index(FilterUserViewModel filter)
        {
            var result = await _userService.FilterAsync(filter);
            return View(result);
        }
        #endregion

        #region Details
        // GET: UserController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var user = await _userService.GetByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var userDetail = new UserViewModel
            {
                Id = id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                UserName = user.UserName,
                IsActive = user.IsActive,
            };

            return View(userDetail);
        }
        #endregion

        #region Create
        // GET: UserController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateUserViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }


            if (await _userService.IsExistUserName(viewModel.UserName.Trim(), null))
            {
                ModelState.AddModelError("UserName", "نام کاربری وارد شده قبلا ثبت نام کرده است");
                return View(viewModel);
            }

            if (await _userService.IsExistEmail(viewModel.Email.Trim().ToLower(), null))
            {
                ModelState.AddModelError("Email", "ایمیل وارد شده قبلا ثبت نام کرده است");
                return View(viewModel);
            }

            var user = new User
            {
                FirstName = viewModel.FirstName,
                LastName = viewModel.LastName,
                Email = viewModel.Email,
                UserName = viewModel.UserName,
                Password = viewModel.Password,
                IsActive = true,
            };

            await _userService.AddAsync(user);

            return RedirectToAction("Index");
        }

        #endregion

        #region Edit
        // GET: UserController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var user = await _userService.GetByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            var viewModel = new EditUserViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                UserName = user.UserName,
                Password = user.Password,
                IsActive = user.IsActive,

            };

            return View(viewModel);
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            if (await _userService.IsExistUserName(viewModel.UserName.Trim(), viewModel.Id))
            {
                ModelState.AddModelError("UserName", "نام کاربری وارد شده قبلا ثبت نام کرده است");
                return View(viewModel);
            }

            if (await _userService.IsExistEmail((viewModel.Email).Trim().ToLower(), viewModel.Id))
            {
                ModelState.AddModelError("Email", "ایمیل وارد شده قبلا ثبت نام کرده است");
                return View(viewModel);
            }

            var user = new User
            {
                Id = viewModel.Id,
                FirstName = viewModel.FirstName,
                LastName = viewModel.LastName,
                Email = viewModel.Email,
                UserName = viewModel.UserName,
                Password = viewModel.Password,
                IsActive = viewModel.IsActive,

            };

            await _userService.UpdateAsync(user);
            return RedirectToAction("Index");

        }
        #endregion

        #region Delete

        // GET: UserController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var user = await _userService.GetByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: UserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _userService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
    #endregion

        #endregion

}

MyApp.Mvc/Controllers/DiscountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyApp.Application.Interfaces;

namespace MyApp.Mvc.Controllers
{
    public class DiscountController : Controller
    {

        #region Fields
        private readonly IDiscountService _discountService;
        #endregion

        #region Constructor
        public DiscountController(IDiscountService discountService)
        {
            _discountService = discountService;
        }
        #endregion

        #region Use Discount By Code

        [Authorize] // Requires user to be authenticated
        [HttpPost]
        public async Task<IActionResult> UseDiscount(string discountCode, int orderId , int userId)
        {

            // Apply the discount to the order
            var resultMessage = await _discountService.ApplyDiscountToOrderAsync(discountCode, orderId, userId);

            // Show the result message to the user
            TempData["DiscountResult"] = resultMessage;

            if (resultMessage == "Success")
            {
                TempData["IsDiscountApplied"] = true;
                TempData["DiscountResult"] = "تخفیف با موفقیت اعمال شد";           
            }    

            return RedirectToAction("ShowOrder", "Order"); // Redirect to show the order
        }

        #endregion

    }
}

MyApp.Mvc/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyApp.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyApp.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyApp.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Discount" asp-action="Index">Discount</a>
                        </li>
                    </ul>
                   
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyApp.Mvc/Areas/Admin/Views/Shared/_Pagination.cshtml
@using MyApp.Domain.ViewModels.Common
@model PagingViewModel

<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="dataTables_paginate paging_simple_numbers d-flex justify-content-center" id="tableGroup_paginate">
            <ul class="pagination">
                @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                {
                    <li class="paginate_button page-item @(Model.Page==i?"active":"")">
                        <a onclick="fillPageId('@i')" aria-controls="tableGroup" data-dt-idx="@i" tabindex="0" class="page-link">
                            @i
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>